export const C = {
  counters: 'counters',
  users: 'users',
  refreshTokens: 'refreshTokens',
  apiKeys: 'apiKeys',
  auditLog: 'auditLog',
  clients: 'clients',
  jobGroups: 'jobGroups',
  zones: 'zones',
  locations: 'locations',
  materials: 'materials',
  serviceTypes: 'serviceTypes',
  truckTypes: 'truckTypes',
  vehicles: 'vehicles',
  drivers: 'drivers',
  palletMovementTypes: 'palletMovementTypes',
  podTemplates: 'podTemplates',
  statusCodes: 'statusCodes',
  holidays: 'holidays',
  resourceBlocks: 'resourceBlocks',
  deliveryOrders: 'deliveryOrders',
  shipments: 'shipments',
} as const;
