import type { FastifyPluginAsyncZod } from 'fastify-type-provider-zod';
import { apiKeyRoutes } from './modules/api-keys/api-keys.routes.js';
import { authRoutes } from './modules/auth/auth.routes.js';
import { blockRoutes } from './modules/availability/blocks.routes.js';
import { eventRoutes } from './modules/execution/events.routes.js';
import { importRoutes } from './modules/imports/imports.routes.js';
import { masterRoutes } from './modules/master/master.routes.js';
import { orderRoutes } from './modules/orders/orders.routes.js';
import { podTemplateRoutes } from './modules/pod-templates/pod-templates.routes.js';
import { podRoutes } from './modules/pods/pods.routes.js';
import { driverRoutes } from './modules/shipments/driver.routes.js';
import { shipmentRoutes } from './modules/shipments/shipments.routes.js';
import { uploadRoutes } from './modules/storage/uploads.routes.js';
import { userRoutes } from './modules/users/users.routes.js';

export const apiRoutes: FastifyPluginAsyncZod = async (api) => {
  await api.register(authRoutes);
  await api.register(userRoutes);
  await api.register(apiKeyRoutes);
  await api.register(masterRoutes);
  await api.register(orderRoutes);
  await api.register(podTemplateRoutes);
  await api.register(importRoutes);
  await api.register(blockRoutes);
  await api.register(shipmentRoutes);
  await api.register(driverRoutes);
  await api.register(eventRoutes);
  await api.register(uploadRoutes);
  await api.register(podRoutes);
};
